### ISSUE TITLE
Zapomniałeś zapłacić za feverpage

### ISSUE THREAD

**Issue by ProgramistaZpolski** [SoGreeno/pygamethingidunno#1]
wygasła ci domena

**Comment by ProgramistaZpolski** [comment]
also pls nie uczyć się pythona

python to kasztan

**Comment by SoGreeno** [comment]
tak wiem że wygasła mi domena. tak naprawdę ono kosztowało 1zł. dam je na edu.org lub eu.org

oraz dlaczego mam sie nie użyć pyhtona. mam dwie książki tego

**Comment by ProgramistaZpolski** [comment]
Otóż, python to zło z kilku powodów.
1. Jak dasz za mało spacji to nie działa
2. Jest wolny
Also usuń może folder .github
To workflows co tam dodałeś co nie wiedziałeś co to jest - jest to coś co nie działa z pythonem

**Comment by chickeeen** [comment]
daj mu spokój
jak chce niech się uczy


btw. to ci potem pull requesta wysle bo cos zepsules tylko n a p r a w i e p y t h o n a b o m a z a w a ł

**Comment by SoGreeno** [comment]
ale już nie robie pythona mam go odinstalowanego z niewiadomychprzyczyn
